api_key = input("Please input API Key : ")
print('api key inserted')
private_key = input("Please input Private Key : ")
print('Private Key inserted')
market = input("Please input Market Pair : ")
print('Market Pair : ' + market)
price_decimals = input("Please input Price Decimal: ")
print('Price Decimal : ' + price_decimals)
quantity_decimals = input("Please input Qty Decimal: ")
print('Qty Decimal : ' + quantity_decimals)

with open('credential.txt', 'w') as f:
        f.write(api_key)
        f.write("\n")
        f.write(private_key)
        f.write("\n")
        f.write(market)
        f.write("\n")
        f.write(price_decimals)
        f.write("\n")
        f.write(quantity_decimals)        